### ISSUE TITLE
Crash when selecting daughter card

### ISSUE THREAD

**Issue by silopolis** [jethornton/7i92#2]
Software crashes with the following error when selecting daughter card in machine/configuration setup:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lib7i92/utilities.py", line 56, in cardChanged
    parent.jointTabs.setTabVisible(5, True)
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'
```

**Comment by jethornton** [comment]
I confirmed the error with Python 3.7.3 and will change that to work with at least 3.6.

JT

**Comment by silopolis** [comment]
Le lun. 7 mars 2022 à 17:24, jethornton ***@***.***> a écrit :

> Closed #2 <https://github.com/jethornton/7i92/issues/2> via e67c1aa
> <https://github.com/jethornton/7i92/commit/e67c1aa8cdefcd9bef4d8b156810da3dfc12bf09>
> .
>

Sweeeet!
Are packages autobuilt?

>
